# Generated by Django 2.0.1 on 2018-01-14 06:40

from django.db import migrations, models
import django_autoslugfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('dias', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2, null=True)),
                ('modo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Te', 'Teórico'), ('PR', 'Práctico')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Horarios de Materias',
                'verbose_name': 'Horario Materia',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('año', models.CharField(blank=True, choices=[('1', '1°'), ('2', '2°'), ('3', '3°'), ('4', '4°'), ('5', '5°'), ('6', '6°'), ('7', '7°')], max_length=1, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('AN', 'Anual'), ('1C', 'Primer Cuatrimetre'), ('2C', 'Segundo Cuatrimestre')], max_length=2, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('correlativas_aprobar', models.ManyToManyField(related_name='_materia_correlativas_aprobar_+', to='materia.Materia')),
                ('correlativas_cursar', models.ManyToManyField(related_name='_materia_correlativas_cursar_+', to='materia.Materia')),
                ('planes_estudio', models.ManyToManyField(to='facultad.PlanEstudio')),
                ('profesores', models.ManyToManyField(to='facultad.Profesor')),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'verbose_name': 'Materia',
            },
        ),
    ]
