# Generated by Django 2.1.2 on 2018-10-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidad', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomateria',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Aula'),
        ),
        migrations.AddField(
            model_name='horariomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='materia.Materia'),
        ),
    ]
