# Generated by Django 2.0.1 on 2018-01-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_auto_20180114_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='slug',
        ),
    ]
