# Generated by Django 2.1.1 on 2018-09-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0005_auto_20180929_1734'),
        ('materia', '0003_remove_materia_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('Te', 'Teórico'), ('PR', 'Práctico')], max_length=2)),
            ],
            options={
                'verbose_name': 'Materia Profesor',
                'verbose_name_plural': 'Materias Profesores',
            },
        ),
        migrations.RemoveField(
            model_name='horariomateria',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='profesores',
        ),
        migrations.AddField(
            model_name='modoprofesor',
            name='horario_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.HorarioMateria'),
        ),
        migrations.AddField(
            model_name='modoprofesor',
            name='profesores',
            field=models.ManyToManyField(to='facultad.Profesor'),
        ),
    ]
