# Generated by Django 2.1.1 on 2018-09-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_auto_20180929_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariomateria',
            options={'verbose_name': 'Horario Materia', 'verbose_name_plural': 'Horarios de Materia'},
        ),
    ]
