# Generated by Django 2.1.1 on 2018-09-30 19:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_auto_20180929_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomateria',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=2, null=True),
        ),
    ]
