# Generated by Django 2.1.1 on 2018-10-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0008_auto_20181007_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='correlativas_aprobar',
            field=models.ManyToManyField(blank=True, related_name='_materia_correlativas_aprobar_+', to='materia.Materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='correlativas_cursar',
            field=models.ManyToManyField(blank=True, related_name='_materia_correlativas_cursar_+', to='materia.Materia'),
        ),
    ]
