# Generated by Django 2.1.1 on 2018-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0009_auto_20181007_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modoprofesor',
            name='modo',
            field=models.CharField(choices=[('TE', 'Teórico'), ('PR', 'Práctico')], max_length=2),
        ),
    ]
