# Generated by Django 2.1.1 on 2018-10-09 11:38

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0010_auto_20181007_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
    ]
