# Generated by Django 2.1.1 on 2018-10-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0011_materia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='materia.Materia'),
        ),
        migrations.AlterField(
            model_name='modoprofesor',
            name='horario_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modo_profesores', to='materia.HorarioMateria'),
        ),
    ]
