# Generated by Django 2.1.1 on 2018-10-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0012_auto_20181009_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modoprofesor',
            name='horario_materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modo_profesores', to='materia.HorarioMateria'),
        ),
    ]
