# Generated by Django 2.0.1 on 2018-01-14 06:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_autoslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'verbose_name': 'Aula',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('extra', models.CharField(blank=True, max_length=400, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('pagina', models.URLField(blank=True, help_text='URL página web', null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ('nombre', 'sigla'),
                'verbose_name_plural': 'Universidades',
                'verbose_name': 'Universidad',
            },
        ),
    ]
