# Generated by Django 2.1.2 on 2018-10-10 16:14

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_auto_20181010_0720'),
    ]

    operations = [
        CreateExtension('postgis')
    ]
