# Generated by Django 2.0.1 on 2018-01-14 06:50

from django.db import migrations, models
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_auto_20180114_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(max_length=150, unique=True),
        ),
    ]
