# Generated by Django 2.0.1 on 2018-01-14 06:52

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_auto_20180114_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
