# Generated by Django 2.0.1 on 2018-01-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_auto_20180114_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='universidad',
            name='slug',
        ),
    ]
