# Generated by Django 2.1.1 on 2018-09-30 01:10

from django.db import migrations, models
import django.db.models.deletion
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0006_auto_20180929_1836'),
        ('universidad', '0007_aula_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='universidad',
        ),
        migrations.AddField(
            model_name='aula',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facultad.Facultad'),
        ),
        migrations.AddField(
            model_name='aula',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(default=1, max_length=255, title_field=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universidad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(default=1, max_length=255, title_field=None, unique=True),
            preserve_default=False,
        ),
    ]
