# Generated by Django 2.1.1 on 2018-09-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0008_auto_20180929_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='facultad',
        ),
        migrations.AddField(
            model_name='aula',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.Universidad'),
        ),
    ]
