# Generated by Django 2.1.1 on 2018-10-09 12:24

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0010_auto_20180930_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
    ]
