# Generated by Django 2.1.1 on 2018-09-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0005_auto_20180929_1734'),
        ('user', '0002_remove_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='universidad',
        ),
        migrations.AddField(
            model_name='user',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='facultad.Facultad'),
        ),
    ]
