# Generated by Django 2.1.1 on 2018-09-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180929_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username', 'last_name', 'first_name'), 'permissions': (('alumno_user', 'alumno'), ('personal_user', 'personal')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
