# Generated by Django 2.1.1 on 2018-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180929_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username', 'last_name', 'first_name'), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ES', 'Estudiante'), ('PE', 'Personal')], default='ES', max_length=2),
        ),
    ]
