# Generated by Django 2.1.1 on 2018-09-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='slug',
        ),
    ]
