# Generated by Django 2.1.1 on 2018-09-30 19:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_remove_imagen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=14, null=True),
        ),
    ]
