# Generated by Django 2.0.1 on 2018-01-14 06:40

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_autoslugfield.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion', models.CharField(blank=True, choices=[('1.0', '1 año'), ('1.5', '1 año y medio'), ('2.0', '2 años'), ('2.5', '2 años y medio'), ('3.0', '3 años'), ('3.5', '3 años y medio'), ('4.0', '4 años'), ('4.5', '4 años y medio'), ('5.0', '5 años'), ('5.5', '5 años y medio'), ('6.0', '6 años'), ('6.5', '6 años y medio'), ('7.0', '7 años')], max_length=3, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('AD', 'A Distancia'), ('CC', 'Ciclo Complementación Curricular'), ('CL', 'Ciclo Licenciatura'), ('GR', 'Grado'), ('PD', 'Post Grado'), ('PG', 'Pre Grado')], max_length=2, null=True)),
                ('trabajo_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
                'verbose_name': 'Carrera',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoFacultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('extra', models.CharField(blank=True, max_length=400, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Departamentos Facultad',
                'verbose_name': 'Departamento Facultad',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('extra', models.CharField(blank=True, max_length=400, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('siu', models.URLField(blank=True, help_text='URL Siu', null=True)),
                ('aula_virtual', models.URLField(blank=True, help_text='URL Aula Virtual', null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.DateField(blank=True, choices=[(datetime.date(2019, 1, 1), '2019'), (datetime.date(2018, 1, 1), '2018'), (datetime.date(2017, 1, 1), '2017'), (datetime.date(2016, 1, 1), '2016'), (datetime.date(2015, 1, 1), '2015'), (datetime.date(2014, 1, 1), '2014'), (datetime.date(2013, 1, 1), '2013'), (datetime.date(2012, 1, 1), '2012'), (datetime.date(2011, 1, 1), '2011'), (datetime.date(2010, 1, 1), '2010'), (datetime.date(2009, 1, 1), '2009'), (datetime.date(2008, 1, 1), '2008'), (datetime.date(2007, 1, 1), '2007'), (datetime.date(2006, 1, 1), '2006'), (datetime.date(2005, 1, 1), '2005'), (datetime.date(2004, 1, 1), '2004'), (datetime.date(2003, 1, 1), '2003'), (datetime.date(2002, 1, 1), '2002'), (datetime.date(2001, 1, 1), '2001'), (datetime.date(2000, 1, 1), '2000'), (datetime.date(1999, 1, 1), '1999'), (datetime.date(1998, 1, 1), '1998'), (datetime.date(1997, 1, 1), '1997'), (datetime.date(1996, 1, 1), '1996'), (datetime.date(1995, 1, 1), '1995'), (datetime.date(1994, 1, 1), '1994'), (datetime.date(1993, 1, 1), '1993'), (datetime.date(1992, 1, 1), '1992'), (datetime.date(1991, 1, 1), '1991'), (datetime.date(1990, 1, 1), '1990')], null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Carrera')),
            ],
            options={
                'verbose_name_plural': 'Planes de Estudio',
                'verbose_name': 'Plan de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('slug', django_autoslugfield.fields.AutoSlugField(unique=True)),
                ('facultades', models.ManyToManyField(to='facultad.Facultad')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'verbose_name': 'Profesor',
            },
        ),
    ]
