# Generated by Django 2.1.2 on 2018-10-10 10:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_autoslugfield.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion', models.CharField(blank=True, choices=[('1.0', '1 año'), ('1.5', '1 año y medio'), ('2.0', '2 años'), ('2.5', '2 años y medio'), ('3.0', '3 años'), ('3.5', '3 años y medio'), ('4.0', '4 años'), ('4.5', '4 años y medio'), ('5.0', '5 años'), ('5.5', '5 años y medio'), ('6.0', '6 años'), ('6.5', '6 años y medio'), ('7.0', '7 años')], max_length=3, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('AD', 'A Distancia'), ('CC', 'Ciclo Complementación Curricular'), ('CL', 'Ciclo Licenciatura'), ('GR', 'Grado'), ('PD', 'Post Grado'), ('PG', 'Pre Grado')], max_length=2, null=True)),
                ('trabajo_final', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoFacultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('extra', models.CharField(blank=True, max_length=400, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Departamento Facultad',
                'verbose_name_plural': 'Departamentos Facultad',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('extra', models.CharField(blank=True, max_length=400, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('siu', models.URLField(blank=True, help_text='URL Siu', null=True)),
                ('aula_virtual', models.URLField(blank=True, help_text='URL Aula Virtual', null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(blank=True, choices=[('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], max_length=4, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Carrera')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
