# Generated by Django 2.0.1 on 2018-01-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0002_auto_20180114_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentofacultad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Pais'),
        ),
        migrations.AlterField(
            model_name='departamentofacultad',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Provincia'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Pais'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Provincia'),
        ),
    ]
