# Generated by Django 2.0.1 on 2018-01-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0003_auto_20180114_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='departamentofacultad',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='slug',
        ),
    ]
