# Generated by Django 2.1.1 on 2018-09-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0004_auto_20180114_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='facultades',
        ),
        migrations.AddField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
