# Generated by Django 2.1.1 on 2018-09-30 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0006_auto_20180929_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='universidad.Universidad'),
        ),
    ]
