# Generated by Django 2.1.1 on 2018-09-30 01:45

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0007_auto_20180929_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(default=1, max_length=255, title_field=None, unique=True),
            preserve_default=False,
        ),
    ]
