# Generated by Django 2.1.1 on 2018-09-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0009_departamentofacultad_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentofacultad',
            name='slug',
        ),
    ]
