# Generated by Django 2.1.1 on 2018-09-30 19:10

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0010_remove_departamentofacultad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentofacultad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(default='efew', max_length=255, title_field=None),
            preserve_default=False,
        ),
    ]
