# Generated by Django 2.1.1 on 2018-09-30 19:14

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0013_departamentofacultad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
    ]
