# Generated by Django 2.1.1 on 2018-09-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0014_auto_20180930_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentofacultad',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='facultad.Facultad'),
        ),
    ]
