# Generated by Django 2.1.1 on 2018-09-30 20:37

from django.db import migrations
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0015_auto_20180930_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
    ]
