# Generated by Django 2.1.1 on 2018-09-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0016_auto_20180930_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='facultad.DepartamentoFacultad'),
        ),
    ]
