# Generated by Django 2.1.1 on 2018-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0019_carrera_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='activo',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
