# Generated by Django 2.1.1 on 2018-10-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0020_auto_20181007_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
