# Generated by Django 2.1.1 on 2018-10-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0021_auto_20181007_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
