# Generated by Django 2.1.1 on 2018-10-08 01:11

from django.db import migrations, models
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0022_auto_20181007_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
